### ISSUE TITLE
descriptors for a solution

### ISSUE THREAD

**Issue by digcatcom** [jpotts/alfresco-addon-descriptor#3]
hi jeff

I was thinking about this a bit more, and thought about when a project solves a problem, using the different tiers in alfresco, but see thats covered in https://github.com/jpotts/alfresco-addon-descriptor/blob/master/src/main/resources/addon-descriptor-schema.json#L103 so really only a link for docs perhaps would be useful.

**Comment by digcatcom** [comment]
hi jeff, thinking about this even more, wouldnt it be a better plan to get alfresco to check a stub file is present and completed, when building the archetypes ?  similar to nuxeo's manifest files which are mandatory.

**Comment by jpotts** [comment]
I do think it would be helpful if Alfresco checked for the manifest, but I think this is still useful without that, so that's not a blocker. I'm hoping to get some momentum going, then we can point to it as something devs are willing to do and hopefully start to work it into the Alfresco toolset where it makes sense.
